name: Infra CI

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
  pull_request:
    branches: [main]
    paths:
      - 'infra/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - uses: actions/setup-node@v5
        with:
          node-version: '20'

      - run: npm install -g aws-cdk

      - run: cdk synth
